version: '3'

services:
  globalDB:
    image: postgres:15.3
    container_name: global-services
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data