import { Navbar } from "@/components/navbar"
import "../../globals.css"
import { Footer } from "@/components/Footer"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-jordy-blue-100 blue-300 to-jordy-blue-400 h-64 w-full">
        <Navbar/>
        {children}
        <Footer />
        </body>
    </html>
  )
}
